default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 30
  host: localhost
development:
  <<: *default
  database: restaurant_development
  
test:
  <<: *default
  database: restaurant_test

production:
  <<: *default
  database: restaurant_production
